# Generated by Django 2.2.10 on 2020-06-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=2000)),
            ],
        ),
    ]
